export type Post = {
    slugs: string[];
    content: string;
    fileName: string;
    meta: { date: Date; description: string; title: string };
};

export const postsService = {
    async getPosts(): Promise<Post[]> {
        return [
            {
                slugs: ['0', '1', '2', '3', '4', '5'],
                content: 'a content',
                fileName: 'a file 0',
                meta: {
                    date: new Date('2022-04-02T22:55:15.779Z'),
                    description: 'a description',
                    title: 'a title',
                },
            },
            {
                slugs: ['0', '1', '2', '3', '4', '5', '6', '7', '8'],
                content: 'a content',
                fileName: 'a file 1',
                meta: {
                    date: new Date('2022-04-02T22:55:15.779Z'),
                    description: 'a description',
                    title: 'a title',
                },
            },
            {
                slugs: [
                    '0',
                    '1',
                    '2',
                    '3',
                    '4',
                    '5',
                    '6',
                    '7',
                    '8',
                    '9',
                    '10',
                    '11',
                    '12',
                    '13',
                    '14',
                    '15',
                    '16',
                ],
                content: 'a content',
                fileName: 'a file 2',
                meta: {
                    date: new Date('2022-04-02T22:55:15.779Z'),
                    description: 'a description',
                    title: 'a title',
                },
            },
            {
                slugs: [
                    '0',
                    '1',
                    '2',
                    '3',
                    '4',
                    '5',
                    '6',
                    '7',
                    '8',
                    '9',
                    '10',
                    '11',
                    '12',
                    '13',
                    '14',
                    '15',
                ],
                content: 'a content',
                fileName: 'a file 3',
                meta: {
                    date: new Date('2022-04-02T22:55:15.779Z'),
                    description: 'a description',
                    title: 'a title',
                },
            },
            {
                slugs: ['0', '1', '2', '3', '4', '5', '6', '7', '8'],
                content: 'a content',
                fileName: 'a file 4',
                meta: {
                    date: new Date('2022-04-02T22:55:15.779Z'),
                    description: 'a description',
                    title: 'a title',
                },
            },
            {
                slugs: [
                    '0',
                    '1',
                    '2',
                    '3',
                    '4',
                    '5',
                    '6',
                    '7',
                    '8',
                    '9',
                    '10',
                    '11',
                    '12',
                    '13',
                    '14',
                    '15',
                    '16',
                    '17',
                    '18',
                ],
                content: 'a content',
                fileName: 'a file 5',
                meta: {
                    date: new Date('2022-04-02T22:55:15.779Z'),
                    description: 'a description',
                    title: 'a title',
                },
            },
            {
                slugs: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
                content: 'a content',
                fileName: 'a file 6',
                meta: {
                    date: new Date('2022-04-02T22:55:15.779Z'),
                    description: 'a description',
                    title: 'a title',
                },
            },
            {
                slugs: [
                    '0',
                    '1',
                    '2',
                    '3',
                    '4',
                    '5',
                    '6',
                    '7',
                    '8',
                    '9',
                    '10',
                    '11',
                    '12',
                    '13',
                    '14',
                    '15',
                    '16',
                    '17',
                    '18',
                ],
                content: 'a content',
                fileName: 'a file 7',
                meta: {
                    date: new Date('2022-04-02T22:55:15.779Z'),
                    description: 'a description',
                    title: 'a title',
                },
            },
            {
                slugs: ['0', '1', '2', '3', '4', '5', '6'],
                content: 'a content',
                fileName: 'a file 8',
                meta: {
                    date: new Date('2022-04-02T22:55:15.779Z'),
                    description: 'a description',
                    title: 'a title',
                },
            },
            {
                slugs: [
                    '0',
                    '1',
                    '2',
                    '3',
                    '4',
                    '5',
                    '6',
                    '7',
                    '8',
                    '9',
                    '10',
                    '11',
                    '12',
                    '13',
                ],
                content: 'a content',
                fileName: 'a file 9',
                meta: {
                    date: new Date('2022-04-02T22:55:15.779Z'),
                    description: 'a description',
                    title: 'a title',
                },
            },
        ];
    },
} as const;
